StackLayoutExample:

<StackLayoutExample>:
    # orientation: "lr/rl-tb/bt"
    Button:
        text: "Stack 1"
        size_hint: .1, .1
    Button:
        text: "Stack 2"
        size_hint: .1, .1
    Button:
        text: "Stack 3"
        size_hint: .1, .1
    Button:
        text: "Stack 4"
        size_hint: .1, .1
    Button:
        text: "Stack 5"
        size_hint: .1, .1
    Button:
        text: "Stack 6"
        size_hint: .1, .1

<GridLayoutExample@GridLayout>:
    # nomber of rows or cols
    rows: 2
    Button:
        text: "Grid 1"
    Button:
        text: "Grid 2"
    BoxLayoutExample:
    Button:
        text: "Grid 3"

<BoxLayoutExample@BoxLayout>:
    Button:
        text: "Box 1"
        size: dp(10), dp(20)
    Button:
        text: "Box 2"
        size: dp(10), dp(20)
    Button:
        text: "Box 3"
        size: dp(10), dp(20)