MainLayout:

<MainLayout@GridLayout>:
    orientation: "lr-tb"
    cols: 5
    Image:
        source: "images/cake_small.jpg"
        allow_stretch: False
        keep_ratio: False
    Image:
        source: "images/cake.jpg"
        allow_stretch: True
        keep_ratio: True
    Image:
        source: "images/cake.jpg"
        allow_stretch: True
        keep_ratio: False
    Image:
        source: "images/cake_small.jpg"
        allow_stretch: True
        keep_ratio: False
    Image:
        source: "images/cake_small.jpg"