#:import get_color_from_hex kivy.utils.get_color_from_hex
#:import StoryCreator libs.components.story_creator.StoryCreator

<HomePage>:
    md_bg_color: get_color_from_hex("#FFFFFF")

    MDBoxLayout:
        orientation: "vertical"

        # Appbar
        AppBar:

        MDBoxLayout:
            ScrollView:
                bar_wirdth: dp(0)

                MDBoxLayout:
                    adaptive_height: True

                    MDBoxLayout:
                        orientation: "vertical"
                        adaptive_height: True
                        id: timeline

                        # Stories
                        ScrollView:
                            size_hint_y: None
                            height: dp(110)
                            bar_wirdth: dp(0)

                            MDBoxLayout:
                                adaptive_width: True
                                spacing: dp(5)
                                padding: dp(5)

                                # Story Creator
                                StoryCreator:
                                    avatar: root.profile_picture
                                
                                MDBoxLayout:
                                    adaptive_width: True
                                    padding: dp(5)
                                    spacing: dp(5)
                                    id: Stories
                        
                        MDSeparator:

        # Button Navigation Bar
        MDBoxLayout:
            adaptive_height: True
            spacing: dp(10)
            padding: dp(10)

            MDIconButton:
                icon: "home"
            
            MDIconButton:
                icon: "magnify"
            
            MDIconButton:
                icon: "movie"
            
            MDIconButton:
                icon: "heart-outline"
            
            FitImage:
                source: root.profile_picture
                size_hint: None, None
                size: dp(25), dp(25)
                radius: (dp(25), )
                pos_hint: {"center_x": 0.5,"center_y": 0.5}

